server:
  port: 6606

spring:
  application:
    name: xx-xw
  config:
    # spring.profiles.active 在springboot 2.4.0版本开始别标志位过时的，并在3.0移除，下面这个是替代品
    import: application-db_mysql.yml, application-mybatisplus.yml
