

spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
    # 连接超时时间（毫秒）
    timeout: 10000

xxl:
  job:
    accessToken: ''
    admin:
      #addresses: http://192.168.32.26:8480/xxl-job-admin/
      addresses: http://localhost:60000/xxl-job-admin/
    executor:
      address: ''
      appname: mytest
      ip: ''
      logpath: ../xxl-job/jobhandler
      logretentiondays: 30
      port: 10019
server:
  port: 10099
